packages:
  - "apps/*"
  - "!apps/bori-agent-backend"
  - "packages/*"
  - "examples/*"
  - "experimental/*"
overrides:
  read-yaml-file: 2.1.0
  vite: 8.1.0
allowBuilds:
  core-js-pure: true
  esbuild: true
  sharp: true
  workerd: true
